name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
#     - name: Output Run ID
#       run: echo ${{ github.run_id }}

#     - name: Checkout
#       uses: actions/checkout@v3
    
#     - name: Set up QEMU
#       uses: docker/setup-qemu-action@v2
    
#     - name: Set up Docker Buildx
#       uses: docker/setup-buildx-action@v2
    
#     - name: Login to Docker Hub
#       uses: docker/login-action@v2
#       with:
#         username: ${{ secrets.DOCKERHUB_USERNAME }}
#         password: ${{ secrets.DOCKERHUB_TOKEN }}
  
#     - name: Build and push build to registry
#       uses: docker/build-push-action@v4
#       with:
#         context: .
#         push: true
#         tags: artemborzienkov/volley-app:${{ github.run_id }}
        
    - id: ssh
      uses: invi5H/ssh-action@v1
      with:
        SSH_HOST: ${{ secrets.DO_HOST_IP }}
        SSH_USER: root
        SSH_KEY: ${{ secrets.DO_HOST_KEY }}
    - run: ssh ${{ steps.ssh.outputs.SERVER }} echo "SUCCESS_LOGIN"

#     - name: Deploy new image to digital ocean
#       uses: invi5H/ssh-action@v1
#       with:
#         SSH_HOST: ${{ secrets.DO_HOST_IP }}
#         SSH_USER: root
#         SSH_KEY: ${{ secrets.DO_HOST_KEY }}
#         - run: echo "SUCCESS_LOGIN"

