name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
#     - name: Output Run ID
#       run: echo ${{ github.run_id }}

#     - name: Checkout
#       uses: actions/checkout@v3
    
#     - name: Set up QEMU
#       uses: docker/setup-qemu-action@v2
    
#     - name: Set up Docker Buildx
#       uses: docker/setup-buildx-action@v2
    
#     - name: Login to Docker Hub
#       uses: docker/login-action@v2
#       with:
#         username: ${{ secrets.DOCKERHUB_USERNAME }}
#         password: ${{ secrets.DOCKERHUB_TOKEN }}
  
#     - name: Build and push build to registry
#       uses: docker/build-push-action@v4
#       with:
#         context: .
#         push: true
#         tags: artemborzienkov/volley-app:${{ github.run_id }}
        
    - name: ssh scp ssh pipelines
      uses: cross-the-world/ssh-scp-ssh-pipelines@latest
      env:
        WELCOME: "ssh scp ssh pipelines"
        LASTSSH: "Doing something after copying"
      with:
        host: ${{ secrets.DO_HOST_IP }}
        key: ${{ secrets.DO_HOST_KEY }}
        user: root
        connect_timeout: 20s
        first_ssh: |
          echo SUCCESS_LOGIN
#         first_ssh: |
#           rm -rf /home/github/test
#           ls -la  \necho $WELCOME 
#           mkdir -p /home/github/test/test1 && 
#           mkdir -p /home/github/test/test2 &&
#         scp: |
#           './test/*' => /home/github/test/
#           ./test/test1* => /home/github/test/test1/
#           ./test/test*.csv => "/home/github/test/test2/"
#         last_ssh: |
#           echo $LASTSSH && 
#           (mkdir test1/test || true)
#           || ls -la

#     - name: Deploy new image to digital ocean
#       uses: invi5H/ssh-action@v1
#       with:
#         SSH_HOST: ${{ secrets.DO_HOST_IP }}
#         SSH_USER: root
#         SSH_KEY: ${{ secrets.DO_HOST_KEY }}
#         - run: echo SUCCESS_LOGIN

