name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Output Run ID
      run: echo ${{ github.run_id }}

    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
  
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: artemborzienkov/volley-app:${{ github.run_id }}

    - name: DigitalOcean App Platform deployment
      uses: digitalocean/app_action@v1.1.4
      with:
        app_name: starfish-app
        token: ${{ secrets.DO_ACCESS_TOKEN }}
        images: '[{ "name": "app-img", "image": {"registry_type": "DOCKER_HUB", "registry": "artemborzienkov", "repository": "volley-app", "tag": ${{ github.run_id }} }]'
